[package]
authors = ["Kenny"]
name = "goodmetrics"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "goodmetrics"
path = "src/bin/client.rs"

[[bin]]
name = "goodmetricsd"
path = "src/bin/server.rs"


[dependencies]
tokio = { version = "1.23", features = ["full", "tracing"] }
tokio-stream = { version = "0.1.11", features = ["net"]}
console-subscriber = { version = "0.1.8" }

hyper = { version = "0.14.23", features = ["full"] }
tonic = { version = "0.8.3", features = ["tls"]} # , "compression" broken by console-subscriber=0.1.6
tower = { version = "0.4.13" }
webpki = { version = "0.22.0" }
rustls-native-certs = { version = "0.6.2" }
tokio-rustls = { version = "0.23.4", features = ["dangerous_configuration"] }
hyper-rustls = { version = "0.23.2", features = ["http2"] }
rustls-pemfile = "1.0.1"
tower-http = { version = "0.3.5", features = ["add-extension", "util"] }

prost = { version = "0.11.3"}
socket2 = { version = "0.4.7", features = ["all"]}
num_cpus = { version = "1.14.0"}

tokio-postgres = { version = "0.7.7", features = ["with-serde_json-1"]}
postgres-types = { version = "0.2.4", features = ["derive"] }
bb8 = { version = "0.8.0" }
bb8-postgres = { version = "0.8.1" }
bytes = { version = "1.3.0" }
rcgen = { version = "0.10.0" }

serde = {version = "1.0.151", features = ["derive"]}
serde_derive = {version = "1.0.151"}
serde_json = {version = "1.0.91"}
# Disable the default-tls feature. It brings in openssl via native-tls which depends on openssl 1.1. But new ubuntu has v3...
reqwest = { version = "0.11.13", default-features = false, features = [] }

clap = {version = "4.0.29", features = ["derive"]}
# structopt-toml = {version = "0.5.0"}
dirs = {version = "4.0.0"}
lazy_static = {version = "1.4.0"}

env_logger = { version = "0.10.0" }
log = { version = "0.4.17" }
anyhow = { version = "1.0.68" }

itertools = { version = "0.10.5" }
regex = { version = "1.7.0" }
thiserror = { version = "1.0.38" }
futures = { version = "0.3.25" }

[build-dependencies]
tonic-build = {version = "0.8.4", features = []}
