[package]
authors = ["Kenny"]
name = "goodmetrics"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "goodmetrics"
path = "src/bin/client.rs"

[[bin]]
name = "goodmetricsd"
path = "src/bin/server.rs"


[dependencies]
tokio = { version = "1", features = ["full", "tracing"] }
tokio-stream = { version = "0.1.8", features = ["net"]}
console-subscriber = { version = "^0" }

hyper = { version = "0.14", features = ["full"] }
tonic = { version = "0.7", features = ["tls", "compression"]}
tower = { version = "0.4" }
webpki = { version = "0.22.0" }
rustls-native-certs = { version = "0.6" }
tokio-rustls = { version = "0.23.4", features = ["dangerous_configuration"] }
hyper-rustls = { version = "0.23", features = ["http2"] }
rustls-pemfile = "*"
tower-http = { version = "0.3", features = ["add-extension", "util"] }

prost = { version = "0.10.4"}
socket2 = { version = "0.4.2", features = ["all"]}
num_cpus = { version = "1.13.0"}

tokio-postgres = { version = "0.7.5", features = ["with-serde_json-1"]}
postgres-types = { version = "0.2.2", features = ["derive"] }
bb8 = { version = "0.8.0" }
bb8-postgres = { version = "0.8.0" }
bytes = { version = "1.1.0" }
rcgen = { version = "0.9.2" }

serde = {version = "1.0", features = ["derive"]}
serde_derive = {version = "1.0"}
serde_json = {version = "1.0"}
reqwest = { version = "0.11", features = [] }

clap = {version = "3.1.6", features = ["derive"]}
# structopt-toml = {version = "0.5.0"}
dirs = {version = "4.0.0"}
lazy_static = {version = "1.4.0"}

env_logger = { version = "^0.9.0" }
log = { version = "^0.4.14" }

itertools = { version = "0.10.3" }
regex = { version = "1.5.4" }
thiserror = { version = "1.0" }
futures = { version = "0.3.19" }

[build-dependencies]
tonic-build = {version = "0.7.2", features = ["compression"]}
