[package]
authors = ["Kenny"]
name = "goodmetrics_relay"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "goodmetrics"
path = "src/client/client.rs"

[[bin]]
name = "goodmetricsd"
path = "src/server/server.rs"


[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-stream = {version = "0.1.8", features = ["net"]}
tonic = {version = "0.6.2", features = ["tls", "tls-roots", "tls-webpki-roots", "compression"]}
prost = {version = "0.9.0"}
socket2 = {version = "0.4.2", features = ["all"]}
num_cpus = {version = "1.13.0"}
tokio-postgres = {version = "0.7.5"}

serde = {version = "1.0", features = ["derive"]}
serde_derive = {version = "1.0"}
serde_json = {version = "1.0"}

structopt = {version = "^0.3.23"}
structopt-toml = {version = "0.5.0"}
dirs = {version = "4.0.0"}
lazy_static = {version = "1.4.0"}

env_logger = { version = "^0.9.0" }
log = { version = "^0.4.14" }

itertools = { version = "0.10.3" }
regex = { version = "1.5.4" }
cached = { version = "0.28.0" }
thiserror = { version = "1.0" }
futures = { version = "0.3.19" }

[build-dependencies]
tonic-build = {version = "0.6.2", features = ["compression"]}
