[package]
authors = ["Kenny"]
name = "goodmetrics_relay"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "goodmetrics"
path = "src/client/client.rs"

[[bin]]
name = "goodmetricsd"
path = "src/server/server.rs"


[dependencies]
tokio = { version = "1", features = ["full"] }
tonic = {version = "0.5.2", features = ["tls", "tls-roots", "tls-webpki-roots", "compression"]}
prost = {version = "0.8.0"}

serde = {version = "1.0", features = ["derive"]}
serde_json = {version = "1.0"}
serde_with = {version = "1.9.4"}

structopt = {version = "^0.3.23"}
env_logger = { version = "^0.9.0" }
log = { version = "^0.4.14" }

[build-dependencies]
tonic-build = {version = "0.5.2", features = ["compression"]}
