name: Build everything

# Based on the Rezolus workflow: https://github.com/twitter/rezolus/blob/master/.github/workflows/cargo.yml
# Thanks for the reference, Brian.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  cache: 0

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install rustfmt
      run: rustup component add rustfmt
    - name: rustfmt
      run: cargo fmt -- --check
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install clippy
      run: rustup component add clippy
    - name: clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
  macos:
    name: macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: Build
        run: cargo build --release
  musl:
    name: musl
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: install rust musl toolchain
        run: rustup target add x86_64-unknown-linux-musl
      - name: update apt
        run: sudo apt-get update
      - name: install musl-tools
        run: sudo apt-get install -y musl-tools
      - name: build
        run: cargo build --release --target x86_64-unknown-linux-musl
